# assemble_rtf: merge multiple rtfreporter-generated RTF files into one.
#
# The function takes advantage of the known structure produced by
# generate_rtfreport(): each file starts with a document header followed by
# \sectd and closes with a single "}" on its own line.
#
# Assembly strategy:
#   * File 1  -> keep all lines except the closing "}"
#   * File N>1 -> extract lines from the first \sectd onward, drop "}"
#   * Files are joined with a \sect separator (RTF section break)
#   * A single "}" closes the combined document
#
# Optional TOC + bookmarks (v0.0.29):
#   * `toc = c("Table 14.1.1", ...)` adds a clickable Table-of-Contents
#     page at the FRONT of the assembled output.  Each TOC entry is an
#     RTF HYPERLINK field pointing to a per-source-file bookmark, and
#     the page number is rendered via a PAGEREF field so the viewer
#     (Word / Pages) updates it automatically.

# Strip the closing RTF "}" from a line vector.
.rtf_drop_close <- function(lines) {
  n <- length(lines)
  while (n > 0L && !nzchar(trimws(lines[n]))) n <- n - 1L
  if (n > 0L && trimws(lines[n]) == "}") lines[-n] else lines
}

# Extract lines starting from the first \sectd (inclusive), closing "}" removed.
.rtf_extract_section_content <- function(lines) {
  idx <- which(trimws(lines) == "\\sectd")
  if (length(idx) == 0L) {
    stop("No \\sectd found in RTF file. Only rtfreporter-generated files are supported.",
         call. = FALSE)
  }
  .rtf_drop_close(lines[idx[1L]:length(lines)])
}

# Sanitise a string into a valid RTF bookmark name.
# Rules: letters / digits / underscores only; <= 32 chars; must start with
# a letter (we prepend `bk_` if the sanitised result starts with a digit).
.sanitize_bookmark <- function(x) {
  s <- sub("\\.rtf$", "", basename(as.character(x)), ignore.case = TRUE)
  s <- gsub("[^A-Za-z0-9_]", "_", s)
  s <- gsub("_+", "_", s)
  s <- gsub("^_|_$", "", s)
  s <- substr(s, 1L, 32L)
  s <- ifelse(grepl("^[A-Za-z]", s) & nzchar(s), s, paste0("bk_", s))
  s
}

# Insert a `{\*\bkmkstart NAME}{\*\bkmkend NAME}` pair right after the
# first \sectd of `content` (a character vector of RTF lines).
.insert_bookmark <- function(content, bookmark_name) {
  sectd_idx <- which(trimws(content) == "\\sectd")[1L]
  if (is.na(sectd_idx)) return(content)
  bkmk <- sprintf("{\\*\\bkmkstart %s}{\\*\\bkmkend %s}",
                  bookmark_name, bookmark_name)
  c(content[1L:sectd_idx], bkmk,
    if (sectd_idx < length(content)) content[(sectd_idx + 1L):length(content)]
    else character(0))
}

# RTF-escape plain text for inclusion in a TOC entry.  Mirrors the
# escape policy of generate_rtfreport()'s .rtf_escape() (no markup,
# no token replacement).
.toc_escape <- function(x) {
  if (length(x) == 0L || is.na(x)) return("")
  chars <- strsplit(as.character(x), "", fixed = TRUE)[[1L]]
  out <- vapply(chars, function(ch) {
    cp <- utf8ToInt(ch)
    if      (ch == "\\") return("\\\\")
    if      (ch == "{")  return("\\{")
    if      (ch == "}")  return("\\}")
    if      (cp > 127L)  return(sprintf("\\u%d?", cp))
    ch
  }, character(1L))
  paste0(out, collapse = "")
}

# Build the TOC section lines.  The section inherits the document's
# landscape orientation and standard margins; a centred bold title sits
# on top, followed by one HYPERLINK + PAGEREF entry per source file.
# Each entry uses a right-tab stop at column 14400 twips (10") with a
# dot leader so the page number aligns to the right margin.
.build_toc_section <- function(toc_labels, bookmarks, toc_title,
                                toc_leader = c("dot", "none")) {
  toc_leader <- match.arg(toc_leader)
  leader_cmd <- if (toc_leader == "dot") "\\tldot" else ""
  # Right tab at 14400 twips (10 inches) — assumes landscape letter with
  # 0.5" margins.  This is the rtfreporter default writable area.
  tab_cmd <- "\\tqr\\tx14400"

  lines <- c(
    "\\sectd\\sbkpage\\lndscpsxn",
    # Page dimensions: landscape letter (matches generate_rtfreport defaults)
    "\\pgwsxn15840\\pghsxn12240",
    "\\marglsxn864\\margrsxn864\\margtsxn1296\\margbsxn1296",
    # Title block: centred, bold, slightly larger
    sprintf("\\pard\\qc\\b\\fs28 %s\\b0\\fs0\\par",
            .toc_escape(toc_title)),
    "\\pard\\fs18\\par"                  # blank breathing line
  )

  for (i in seq_along(toc_labels)) {
    entry_txt <- .toc_escape(toc_labels[i])
    bm        <- bookmarks[i]
    # Each TOC line: HYPERLINK (clickable) -> tab -> PAGEREF (page #)
    line <- sprintf(
      paste0("\\pard%s%s ",
             "{\\field{\\*\\fldinst HYPERLINK \\\\l \"%s\"}",
             "{\\fldrslt %s}}",
             "\\tab",
             "{\\field{\\*\\fldinst PAGEREF %s \\\\h}",
             "{\\fldrslt 1}}",
             "\\par"),
      tab_cmd, leader_cmd, bm, entry_txt, bm
    )
    lines <- c(lines, line)
  }
  lines
}


#' Assemble multiple RTF files into one
#'
#' `assemble_rtf()` concatenates several RTF files that were generated by
#' [generate_rtfreport()] into a single RTF document.  Each input file
#' becomes one or more sections in the output; the document header (font
#' table, colour table, page settings) is taken from the first input file.
#'
#' Page-number fields work correctly across the assembled document
#' provided the header/footer text uses dynamic tokens:
#'
#' * `{AUTO_PAGE}` — page number updated per page by the RTF viewer.
#' * `{AUTO_TOTAL_PAGES}` — total page count updated by the viewer
#'   across all assembled files.
#'
#' Static tokens (`{TOTAL_PAGES}`) reflect only the page count of the
#' individual source file and will be wrong in the assembled output.
#'
#' @section Table of Contents and bookmarks:
#' Setting `toc =` to a character vector of labels (one per input file)
#' adds a TOC page at the front of the assembled document.  Each label
#' becomes a HYPERLINK field pointing to a per-source-file bookmark
#' inserted right after that section's `\\sectd`.  Page numbers are
#' rendered via a PAGEREF field so the RTF viewer (Word / Pages)
#' updates them automatically when the document opens.
#'
#' Bookmark names are auto-generated from each input file's basename
#' (sanitised to letters / digits / underscores, ≤ 32 chars,
#' prepended with `bookmark_prefix`).  When `toc = NULL` (the default)
#' no TOC and no bookmarks are added — the assembled file is
#' byte-for-byte identical to the pre-v0.0.29 behaviour.
#'
#' @param input_files Character vector of paths to RTF files to combine
#'   (at least 2).
#' @param output_file Path for the assembled output RTF file.
#' @param overwrite Logical; whether to overwrite an existing output file.
#'   Default `FALSE`.
#' @param toc Optional character vector of TOC entry labels, one per
#'   input file.  `NULL` (default) = no TOC, no bookmarks.
#' @param toc_title Centred bold title rendered on the TOC page.
#'   Default `"Table of Contents"`.
#' @param toc_leader `"dot"` (default) draws a dotted leader between
#'   each TOC entry and its page number; `"none"` leaves whitespace.
#' @param bookmark_prefix String prepended to every auto-generated
#'   bookmark name (helps avoid clashes if you later combine multiple
#'   assembled outputs).  Default `"tfl_"`.
#'
#' @return Invisibly returns `output_file`.
#'
#' @examples
#' \dontrun{
#' # No TOC (legacy behaviour)
#' assemble_rtf(
#'   input_files = c("table14_1_1.rtf", "listing16_1.rtf"),
#'   output_file = "tfl_package.rtf",
#'   overwrite   = TRUE
#' )
#'
#' # With clickable Table of Contents
#' assemble_rtf(
#'   input_files = c("t14_1_1.rtf", "t14_2_1.rtf", "l16_1.rtf"),
#'   output_file = "tfl_package.rtf",
#'   toc         = c("Table 14.1.1 Demographics",
#'                   "Table 14.2.1 Adverse Events",
#'                   "Listing 16.1 Subject Disposition"),
#'   overwrite   = TRUE
#' )
#' }
#'
#' @export
assemble_rtf <- function(input_files, output_file, overwrite = FALSE,
                          toc             = NULL,
                          toc_title       = "Table of Contents",
                          toc_leader      = c("dot", "none"),
                          bookmark_prefix = "tfl_") {
  toc_leader <- match.arg(toc_leader)

  if (!is.character(input_files) || length(input_files) < 2L) {
    stop("`input_files` must be a character vector with at least 2 elements.",
         call. = FALSE)
  }
  for (f in input_files) {
    if (!file.exists(f)) stop(sprintf("Input file not found: %s", f),
                              call. = FALSE)
  }
  if (file.exists(output_file) && !isTRUE(overwrite)) {
    stop("`output_file` already exists. Set overwrite = TRUE.", call. = FALSE)
  }

  use_toc <- !is.null(toc)
  if (use_toc) {
    if (!is.character(toc) || length(toc) != length(input_files)) {
      stop("`toc` must be a character vector the same length as `input_files`.",
           call. = FALSE)
    }
    bookmarks <- paste0(bookmark_prefix,
                        .sanitize_bookmark(input_files))
    if (anyDuplicated(bookmarks)) {
      # Disambiguate clashing sanitised names with .1, .2, ...
      tab <- table(bookmarks)
      dups <- names(tab)[tab > 1L]
      for (d in dups) {
        idx <- which(bookmarks == d)
        bookmarks[idx] <- paste0(d, "_", seq_along(idx))
      }
    }
  }

  # ── File 1 ────────────────────────────────────────────────────────────
  lines1 <- readLines(input_files[1L], warn = FALSE)
  body   <- .rtf_drop_close(lines1)

  if (use_toc) {
    # Find the first \sectd in file 1 — TOC goes BEFORE it.
    sectd_idx <- which(trimws(body) == "\\sectd")[1L]
    if (is.na(sectd_idx)) {
      stop("File 1 has no \\sectd; cannot insert TOC.", call. = FALSE)
    }
    toc_lines <- .build_toc_section(toc, bookmarks, toc_title, toc_leader)
    head_lines <- body[seq_len(sectd_idx - 1L)]
    tail_lines <- body[seq.int(sectd_idx, length(body))]
    # Bookmark for file 1 lands right after its \sectd.
    tail_lines <- .insert_bookmark(tail_lines, bookmarks[1L])
    body <- c(head_lines, toc_lines, "\\sect", tail_lines)
  }

  # ── Files 2..N ─────────────────────────────────────────────────────────
  for (i in seq_along(input_files)[-1L]) {
    content <- .rtf_extract_section_content(readLines(input_files[i],
                                                       warn = FALSE))
    if (use_toc) {
      content <- .insert_bookmark(content, bookmarks[i])
    }
    body <- c(body, "\\sect", content)
  }

  body <- c(body, "}")
  writeLines(body, con = output_file, useBytes = TRUE)
  invisible(output_file)
}
