# assemble_rtf: merge multiple rtfreporter-generated RTF files into one.
#
# The function takes advantage of the known structure produced by
# generate_rtfreport(): each file starts with a document header followed by
# \sectd and closes with a single "}" on its own line.
#
# Assembly strategy:
#   * File 1  -> keep all lines except the closing "}"
#   * File N>1 -> extract lines from the first \sectd onward, drop the closing "}"
#   * Files are joined with a \sect separator (RTF section break)
#   * A single "}" closes the combined document

# Strip the closing RTF "}" from a line vector.
.rtf_drop_close <- function(lines) {
  n <- length(lines)
  while (n > 0L && !nzchar(trimws(lines[n]))) n <- n - 1L
  if (n > 0L && trimws(lines[n]) == "}") lines[-n] else lines
}

# Extract lines starting from the first \sectd (inclusive), closing "}" removed.
.rtf_extract_section_content <- function(lines) {
  idx <- which(trimws(lines) == "\\sectd")
  if (length(idx) == 0L) {
    stop("No \\sectd found in RTF file. Only rtfreporter-generated files are supported.",
         call. = FALSE)
  }
  .rtf_drop_close(lines[idx[1L]:length(lines)])
}


#' Assemble multiple RTF files into one
#'
#' `assemble_rtf()` concatenates several RTF files that were generated by
#' [generate_rtfreport()] into a single RTF document.  Each input file becomes
#' one or more sections in the output; the document header (font table, colour
#' table, page settings) is taken from the first input file.
#'
#' Page-number fields work correctly across the assembled document provided the
#' header/footer text uses dynamic tokens:
#' - `{AUTO_PAGE}` -- page number updated per page by the RTF viewer.
#' - `{AUTO_TOTAL_PAGES}` -- total page count updated by the RTF viewer across
#'   all assembled files.
#'
#' Static tokens (`{TOTAL_PAGES}`) reflect only the page count of the
#' individual source file and will be wrong in the assembled output.
#'
#' @param input_files Character vector of paths to RTF files to combine (at
#'   least 2).
#' @param output_file Path for the assembled output RTF file.
#' @param overwrite Logical; whether to overwrite an existing output file.
#'   Default `FALSE`.
#'
#' @return Invisibly returns `output_file`.
#'
#' @examples
#' \dontrun{
#' assemble_rtf(
#'   input_files = c("table14_1_1.rtf", "table14_1_2.rtf", "listing16_1.rtf"),
#'   output_file = "tfl_package.rtf",
#'   overwrite   = TRUE
#' )
#' }
#'
#' @export
assemble_rtf <- function(input_files, output_file, overwrite = FALSE) {
  if (!is.character(input_files) || length(input_files) < 2L) {
    stop("`input_files` must be a character vector with at least 2 elements.", call. = FALSE)
  }
  for (f in input_files) {
    if (!file.exists(f)) stop(sprintf("Input file not found: %s", f), call. = FALSE)
  }
  if (file.exists(output_file) && !isTRUE(overwrite)) {
    stop("`output_file` already exists. Set overwrite = TRUE.", call. = FALSE)
  }

  # File 1: full content minus closing "}"
  lines1 <- readLines(input_files[1L], warn = FALSE)
  body   <- .rtf_drop_close(lines1)

  # Files 2..N: section content (from \sectd onward, closing "}" removed)
  for (f in input_files[-1L]) {
    content <- .rtf_extract_section_content(readLines(f, warn = FALSE))
    body    <- c(body, "\\sect", content)
  }

  body <- c(body, "}")
  writeLines(body, con = output_file, useBytes = TRUE)
  invisible(output_file)
}
